# Generated by Django 2.2.8 on 2019-12-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classword',
            name='classwordlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classword', to='core.ClassWordList'),
        ),
    ]
