# Generated by Django 2.2.7 on 2019-11-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='userwordlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userword', to='core.UserWordList'),
        ),
    ]
