# Generated by Django 2.2.8 on 2019-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191203_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingsystem',
            name='grade_5',
        ),
    ]
