# Generated by Django 2.2.8 on 2019-12-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ratingsystem_grade_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='classtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenttest', to='core.ClassTest'),
        ),
    ]
