# Generated by Django 2.2.7 on 2019-11-24 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191124_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
