# Generated by Django 2.2.7 on 2019-12-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacheraplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAplication',
            new_name='TeacherApplication',
        ),
    ]
