# Generated by Django 2.2.7 on 2019-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191201_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='status',
            field=models.CharField(choices=[('waiting...', 'waiting...'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='waiting...', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'user'), ('teacher', 'teacher')], default='user', max_length=255),
        ),
    ]
